version: '3.4'

services:

  sprite2-deploy:
    build:
      context: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
    command:
      - sprite

  sprite2:
    build:
      context: .
      target: invoke
    environment:
      - LOG_LEVEL=${LOG_LEVEL-DEBUG}
    command: app.sprite_cp '"gASVaQEAAAAAAACMCWZ1bmN0b29sc5SMB3BhcnRpYWyUk5SMF2Nsb3VkcGlja2xlLmNsb3VkcGlj\na2xllIwOX2ZpbGxfZnVuY3Rpb26Uk5QoaAOMD19tYWtlX3NrZWxfZnVuY5STlGgDjA1fYnVpbHRp\nbl90eXBllJOUjAhDb2RlVHlwZZSFlFKUKEsBSwBLAUsCS0NDCmQBfACbAJ0CUwCUTowOdGhpcyBl\neGVjdXRlcyCUhpQpjAFvlIWUjB48aXB5dGhvbi1pbnB1dC02LTA0ZTQwZGE4YjQ1NT6UjAg8bGFt\nYmRhPpRLAUMAlCkpdJRSlEr/////fZSHlFKUfZQojAdnbG9iYWxzlH2UjAhkZWZhdWx0c5ROjARk\naWN0lH2UjAZtb2R1bGWUjAhfX21haW5fX5SMDmNsb3N1cmVfdmFsdWVzlE6MCHF1YWxuYW1llGgT\ndXRShZRSlChoGYwIcmVtb3RlbHmUhZR9lE50lGIu\n"'